### PR TITLE
Warn against "using namespace std;".

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Comment by ThadHouse** [comment]
I thought we warned against all using namespaces?

**Comment by calcmogul** [comment]
That's only in headers within the global namespace.

**Comment by ThadHouse** [comment]
Ah ok.

**Comment by PeterJohnson** [comment]
Do we actually have this anywhere?

**Comment by calcmogul** [comment]
We don't. I have my FRC team use wpiformat as well and I ween them off of "using namespace std;" after a few weeks of intro C++. It's a common review complaint I have that I'd like to automate. Seems like a generally applicable rule. Note that this doesn't affect `using` declarations at all (e.g., `using std::chrono`).

**Pull request merged**
